// this file is automatically generated
module fsgen.opcodes
    open fsgen.types

    let opcode_infos = [
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x00;
            name = "Unreachable";
            text = "unreachable";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x01;
            name = "Nop";
            text = "nop";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x02;
            name = "Block";
            text = "block";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x03;
            name = "Loop";
            text = "loop";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x04;
            name = "If";
            text = "if";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x05;
            name = "Else";
            text = "else";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x0b;
            name = "End";
            text = "end";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x0c;
            name = "Br";
            text = "br";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x0d;
            name = "BrIf";
            text = "br_if";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x0e;
            name = "BrTable";
            text = "br_table";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x0f;
            name = "Return";
            text = "return";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x10;
            name = "Call";
            text = "call";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x11;
            name = "CallIndirect";
            text = "call_indirect";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x1a;
            name = "Drop";
            text = "drop";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x1b;
            name = "Select";
            text = "select";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x20;
            name = "LocalGet";
            text = "local.get";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x21;
            name = "LocalSet";
            text = "local.set";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x22;
            name = "LocalTee";
            text = "local.tee";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x23;
            name = "GlobalGet";
            text = "global.get";
        }
        {
            rtype = None;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x24;
            name = "GlobalSet";
            text = "global.set";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 4;
            prefix = None;
            code = 0x28;
            name = "I32Load";
            text = "i32.load";
        }
        {
            rtype = Some I64;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 8;
            prefix = None;
            code = 0x29;
            name = "I64Load";
            text = "i64.load";
        }
        {
            rtype = Some F32;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 4;
            prefix = None;
            code = 0x2a;
            name = "F32Load";
            text = "f32.load";
        }
        {
            rtype = Some F64;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 8;
            prefix = None;
            code = 0x2b;
            name = "F64Load";
            text = "f64.load";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 1;
            prefix = None;
            code = 0x2c;
            name = "I32Load8S";
            text = "i32.load8_s";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 1;
            prefix = None;
            code = 0x2d;
            name = "I32Load8U";
            text = "i32.load8_u";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 2;
            prefix = None;
            code = 0x2e;
            name = "I32Load16S";
            text = "i32.load16_s";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 2;
            prefix = None;
            code = 0x2f;
            name = "I32Load16U";
            text = "i32.load16_u";
        }
        {
            rtype = Some I64;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 1;
            prefix = None;
            code = 0x30;
            name = "I64Load8S";
            text = "i64.load8_s";
        }
        {
            rtype = Some I64;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 1;
            prefix = None;
            code = 0x31;
            name = "I64Load8U";
            text = "i64.load8_u";
        }
        {
            rtype = Some I64;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 2;
            prefix = None;
            code = 0x32;
            name = "I64Load16S";
            text = "i64.load16_s";
        }
        {
            rtype = Some I64;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 2;
            prefix = None;
            code = 0x33;
            name = "I64Load16U";
            text = "i64.load16_u";
        }
        {
            rtype = Some I64;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 4;
            prefix = None;
            code = 0x34;
            name = "I64Load32S";
            text = "i64.load32_s";
        }
        {
            rtype = Some I64;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 4;
            prefix = None;
            code = 0x35;
            name = "I64Load32U";
            text = "i64.load32_u";
        }
        {
            rtype = None;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 4;
            prefix = None;
            code = 0x36;
            name = "I32Store";
            text = "i32.store";
        }
        {
            rtype = None;
            type1 = Some I32;
            type2 = Some I64;
            type3 = None;
            mem_size = 8;
            prefix = None;
            code = 0x37;
            name = "I64Store";
            text = "i64.store";
        }
        {
            rtype = None;
            type1 = Some I32;
            type2 = Some F32;
            type3 = None;
            mem_size = 4;
            prefix = None;
            code = 0x38;
            name = "F32Store";
            text = "f32.store";
        }
        {
            rtype = None;
            type1 = Some I32;
            type2 = Some F64;
            type3 = None;
            mem_size = 8;
            prefix = None;
            code = 0x39;
            name = "F64Store";
            text = "f64.store";
        }
        {
            rtype = None;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 1;
            prefix = None;
            code = 0x3a;
            name = "I32Store8";
            text = "i32.store8";
        }
        {
            rtype = None;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 2;
            prefix = None;
            code = 0x3b;
            name = "I32Store16";
            text = "i32.store16";
        }
        {
            rtype = None;
            type1 = Some I32;
            type2 = Some I64;
            type3 = None;
            mem_size = 1;
            prefix = None;
            code = 0x3c;
            name = "I64Store8";
            text = "i64.store8";
        }
        {
            rtype = None;
            type1 = Some I32;
            type2 = Some I64;
            type3 = None;
            mem_size = 2;
            prefix = None;
            code = 0x3d;
            name = "I64Store16";
            text = "i64.store16";
        }
        {
            rtype = None;
            type1 = Some I32;
            type2 = Some I64;
            type3 = None;
            mem_size = 4;
            prefix = None;
            code = 0x3e;
            name = "I64Store32";
            text = "i64.store32";
        }
        {
            rtype = Some I32;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x3f;
            name = "MemorySize";
            text = "memory.size";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x40;
            name = "MemoryGrow";
            text = "memory.grow";
        }
        {
            rtype = Some I32;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x41;
            name = "I32Const";
            text = "i32.const";
        }
        {
            rtype = Some I64;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x42;
            name = "I64Const";
            text = "i64.const";
        }
        {
            rtype = Some F32;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x43;
            name = "F32Const";
            text = "f32.const";
        }
        {
            rtype = Some F64;
            type1 = None;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x44;
            name = "F64Const";
            text = "f64.const";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x45;
            name = "I32Eqz";
            text = "i32.eqz";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x46;
            name = "I32Eq";
            text = "i32.eq";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x47;
            name = "I32Ne";
            text = "i32.ne";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x48;
            name = "I32LtS";
            text = "i32.lt_s";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x49;
            name = "I32LtU";
            text = "i32.lt_u";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x4a;
            name = "I32GtS";
            text = "i32.gt_s";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x4b;
            name = "I32GtU";
            text = "i32.gt_u";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x4c;
            name = "I32LeS";
            text = "i32.le_s";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x4d;
            name = "I32LeU";
            text = "i32.le_u";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x4e;
            name = "I32GeS";
            text = "i32.ge_s";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x4f;
            name = "I32GeU";
            text = "i32.ge_u";
        }
        {
            rtype = Some I32;
            type1 = Some I64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x50;
            name = "I64Eqz";
            text = "i64.eqz";
        }
        {
            rtype = Some I32;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x51;
            name = "I64Eq";
            text = "i64.eq";
        }
        {
            rtype = Some I32;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x52;
            name = "I64Ne";
            text = "i64.ne";
        }
        {
            rtype = Some I32;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x53;
            name = "I64LtS";
            text = "i64.lt_s";
        }
        {
            rtype = Some I32;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x54;
            name = "I64LtU";
            text = "i64.lt_u";
        }
        {
            rtype = Some I32;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x55;
            name = "I64GtS";
            text = "i64.gt_s";
        }
        {
            rtype = Some I32;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x56;
            name = "I64GtU";
            text = "i64.gt_u";
        }
        {
            rtype = Some I32;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x57;
            name = "I64LeS";
            text = "i64.le_s";
        }
        {
            rtype = Some I32;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x58;
            name = "I64LeU";
            text = "i64.le_u";
        }
        {
            rtype = Some I32;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x59;
            name = "I64GeS";
            text = "i64.ge_s";
        }
        {
            rtype = Some I32;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x5a;
            name = "I64GeU";
            text = "i64.ge_u";
        }
        {
            rtype = Some I32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x5b;
            name = "F32Eq";
            text = "f32.eq";
        }
        {
            rtype = Some I32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x5c;
            name = "F32Ne";
            text = "f32.ne";
        }
        {
            rtype = Some I32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x5d;
            name = "F32Lt";
            text = "f32.lt";
        }
        {
            rtype = Some I32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x5e;
            name = "F32Gt";
            text = "f32.gt";
        }
        {
            rtype = Some I32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x5f;
            name = "F32Le";
            text = "f32.le";
        }
        {
            rtype = Some I32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x60;
            name = "F32Ge";
            text = "f32.ge";
        }
        {
            rtype = Some I32;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x61;
            name = "F64Eq";
            text = "f64.eq";
        }
        {
            rtype = Some I32;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x62;
            name = "F64Ne";
            text = "f64.ne";
        }
        {
            rtype = Some I32;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x63;
            name = "F64Lt";
            text = "f64.lt";
        }
        {
            rtype = Some I32;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x64;
            name = "F64Gt";
            text = "f64.gt";
        }
        {
            rtype = Some I32;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x65;
            name = "F64Le";
            text = "f64.le";
        }
        {
            rtype = Some I32;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x66;
            name = "F64Ge";
            text = "f64.ge";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x67;
            name = "I32Clz";
            text = "i32.clz";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x68;
            name = "I32Ctz";
            text = "i32.ctz";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x69;
            name = "I32Popcnt";
            text = "i32.popcnt";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x6a;
            name = "I32Add";
            text = "i32.add";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x6b;
            name = "I32Sub";
            text = "i32.sub";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x6c;
            name = "I32Mul";
            text = "i32.mul";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x6d;
            name = "I32DivS";
            text = "i32.div_s";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x6e;
            name = "I32DivU";
            text = "i32.div_u";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x6f;
            name = "I32RemS";
            text = "i32.rem_s";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x70;
            name = "I32RemU";
            text = "i32.rem_u";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x71;
            name = "I32And";
            text = "i32.and";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x72;
            name = "I32Or";
            text = "i32.or";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x73;
            name = "I32Xor";
            text = "i32.xor";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x74;
            name = "I32Shl";
            text = "i32.shl";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x75;
            name = "I32ShrS";
            text = "i32.shr_s";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x76;
            name = "I32ShrU";
            text = "i32.shr_u";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x77;
            name = "I32Rotl";
            text = "i32.rotl";
        }
        {
            rtype = Some I32;
            type1 = Some I32;
            type2 = Some I32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x78;
            name = "I32Rotr";
            text = "i32.rotr";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x79;
            name = "I64Clz";
            text = "i64.clz";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x7a;
            name = "I64Ctz";
            text = "i64.ctz";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x7b;
            name = "I64Popcnt";
            text = "i64.popcnt";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x7c;
            name = "I64Add";
            text = "i64.add";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x7d;
            name = "I64Sub";
            text = "i64.sub";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x7e;
            name = "I64Mul";
            text = "i64.mul";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x7f;
            name = "I64DivS";
            text = "i64.div_s";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x80;
            name = "I64DivU";
            text = "i64.div_u";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x81;
            name = "I64RemS";
            text = "i64.rem_s";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x82;
            name = "I64RemU";
            text = "i64.rem_u";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x83;
            name = "I64And";
            text = "i64.and";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x84;
            name = "I64Or";
            text = "i64.or";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x85;
            name = "I64Xor";
            text = "i64.xor";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x86;
            name = "I64Shl";
            text = "i64.shl";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x87;
            name = "I64ShrS";
            text = "i64.shr_s";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x88;
            name = "I64ShrU";
            text = "i64.shr_u";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x89;
            name = "I64Rotl";
            text = "i64.rotl";
        }
        {
            rtype = Some I64;
            type1 = Some I64;
            type2 = Some I64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x8a;
            name = "I64Rotr";
            text = "i64.rotr";
        }
        {
            rtype = Some F32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x8b;
            name = "F32Abs";
            text = "f32.abs";
        }
        {
            rtype = Some F32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x8c;
            name = "F32Neg";
            text = "f32.neg";
        }
        {
            rtype = Some F32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x8d;
            name = "F32Ceil";
            text = "f32.ceil";
        }
        {
            rtype = Some F32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x8e;
            name = "F32Floor";
            text = "f32.floor";
        }
        {
            rtype = Some F32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x8f;
            name = "F32Trunc";
            text = "f32.trunc";
        }
        {
            rtype = Some F32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x90;
            name = "F32Nearest";
            text = "f32.nearest";
        }
        {
            rtype = Some F32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x91;
            name = "F32Sqrt";
            text = "f32.sqrt";
        }
        {
            rtype = Some F32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x92;
            name = "F32Add";
            text = "f32.add";
        }
        {
            rtype = Some F32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x93;
            name = "F32Sub";
            text = "f32.sub";
        }
        {
            rtype = Some F32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x94;
            name = "F32Mul";
            text = "f32.mul";
        }
        {
            rtype = Some F32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x95;
            name = "F32Div";
            text = "f32.div";
        }
        {
            rtype = Some F32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x96;
            name = "F32Min";
            text = "f32.min";
        }
        {
            rtype = Some F32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x97;
            name = "F32Max";
            text = "f32.max";
        }
        {
            rtype = Some F32;
            type1 = Some F32;
            type2 = Some F32;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x98;
            name = "F32Copysign";
            text = "f32.copysign";
        }
        {
            rtype = Some F64;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x99;
            name = "F64Abs";
            text = "f64.abs";
        }
        {
            rtype = Some F64;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x9a;
            name = "F64Neg";
            text = "f64.neg";
        }
        {
            rtype = Some F64;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x9b;
            name = "F64Ceil";
            text = "f64.ceil";
        }
        {
            rtype = Some F64;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x9c;
            name = "F64Floor";
            text = "f64.floor";
        }
        {
            rtype = Some F64;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x9d;
            name = "F64Trunc";
            text = "f64.trunc";
        }
        {
            rtype = Some F64;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x9e;
            name = "F64Nearest";
            text = "f64.nearest";
        }
        {
            rtype = Some F64;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0x9f;
            name = "F64Sqrt";
            text = "f64.sqrt";
        }
        {
            rtype = Some F64;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xa0;
            name = "F64Add";
            text = "f64.add";
        }
        {
            rtype = Some F64;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xa1;
            name = "F64Sub";
            text = "f64.sub";
        }
        {
            rtype = Some F64;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xa2;
            name = "F64Mul";
            text = "f64.mul";
        }
        {
            rtype = Some F64;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xa3;
            name = "F64Div";
            text = "f64.div";
        }
        {
            rtype = Some F64;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xa4;
            name = "F64Min";
            text = "f64.min";
        }
        {
            rtype = Some F64;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xa5;
            name = "F64Max";
            text = "f64.max";
        }
        {
            rtype = Some F64;
            type1 = Some F64;
            type2 = Some F64;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xa6;
            name = "F64Copysign";
            text = "f64.copysign";
        }
        {
            rtype = Some I32;
            type1 = Some I64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xa7;
            name = "I32WrapI64";
            text = "i32.wrap_i64";
        }
        {
            rtype = Some I32;
            type1 = Some F32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xa8;
            name = "I32TruncF32S";
            text = "i32.trunc_f32_s";
        }
        {
            rtype = Some I32;
            type1 = Some F32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xa9;
            name = "I32TruncF32U";
            text = "i32.trunc_f32_u";
        }
        {
            rtype = Some I32;
            type1 = Some F64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xaa;
            name = "I32TruncF64S";
            text = "i32.trunc_f64_s";
        }
        {
            rtype = Some I32;
            type1 = Some F64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xab;
            name = "I32TruncF64U";
            text = "i32.trunc_f64_u";
        }
        {
            rtype = Some I64;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xac;
            name = "I64ExtendI32S";
            text = "i64.extend_i32_s";
        }
        {
            rtype = Some I64;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xad;
            name = "I64ExtendI32U";
            text = "i64.extend_i32_u";
        }
        {
            rtype = Some I64;
            type1 = Some F32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xae;
            name = "I64TruncF32S";
            text = "i64.trunc_f32_s";
        }
        {
            rtype = Some I64;
            type1 = Some F32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xaf;
            name = "I64TruncF32U";
            text = "i64.trunc_f32_u";
        }
        {
            rtype = Some I64;
            type1 = Some F64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xb0;
            name = "I64TruncF64S";
            text = "i64.trunc_f64_s";
        }
        {
            rtype = Some I64;
            type1 = Some F64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xb1;
            name = "I64TruncF64U";
            text = "i64.trunc_f64_u";
        }
        {
            rtype = Some F32;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xb2;
            name = "F32ConvertI32S";
            text = "f32.convert_i32_s";
        }
        {
            rtype = Some F32;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xb3;
            name = "F32ConvertI32U";
            text = "f32.convert_i32_u";
        }
        {
            rtype = Some F32;
            type1 = Some I64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xb4;
            name = "F32ConvertI64S";
            text = "f32.convert_i64_s";
        }
        {
            rtype = Some F32;
            type1 = Some I64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xb5;
            name = "F32ConvertI64U";
            text = "f32.convert_i64_u";
        }
        {
            rtype = Some F32;
            type1 = Some F64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xb6;
            name = "F32DemoteF64";
            text = "f32.demote_f64";
        }
        {
            rtype = Some F64;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xb7;
            name = "F64ConvertI32S";
            text = "f64.convert_i32_s";
        }
        {
            rtype = Some F64;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xb8;
            name = "F64ConvertI32U";
            text = "f64.convert_i32_u";
        }
        {
            rtype = Some F64;
            type1 = Some I64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xb9;
            name = "F64ConvertI64S";
            text = "f64.convert_i64_s";
        }
        {
            rtype = Some F64;
            type1 = Some I64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xba;
            name = "F64ConvertI64U";
            text = "f64.convert_i64_u";
        }
        {
            rtype = Some F64;
            type1 = Some F32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xbb;
            name = "F64PromoteF32";
            text = "f64.promote_f32";
        }
        {
            rtype = Some I32;
            type1 = Some F32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xbc;
            name = "I32ReinterpretF32";
            text = "i32.reinterpret_f32";
        }
        {
            rtype = Some I64;
            type1 = Some F64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xbd;
            name = "I64ReinterpretF64";
            text = "i64.reinterpret_f64";
        }
        {
            rtype = Some F32;
            type1 = Some I32;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xbe;
            name = "F32ReinterpretI32";
            text = "f32.reinterpret_i32";
        }
        {
            rtype = Some F64;
            type1 = Some I64;
            type2 = None;
            type3 = None;
            mem_size = 0;
            prefix = None;
            code = 0xbf;
            name = "F64ReinterpretI64";
            text = "f64.reinterpret_i64";
        }
    ]
